blank_issues_enabled: true
contact_links:
  - name: Discord Community Support
    url: https://discord.gg/CjrCrNzd3F
    about: If you have questions or need help implementing Velopack in your app, please visit our Discord community.